# Generated by Django 3.2.6 on 2021-08-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dispatch',
            new_name='dispatched',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_id',
        ),
    ]
