# Generated by Django 3.2.6 on 2021-08-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210811_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dispatched',
            new_name='dispatch',
        ),
    ]
