# Generated by Django 3.2.6 on 2021-08-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_dispatched_order_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.items'),
            preserve_default=False,
        ),
    ]
